"""Add devise to Client

Revision ID: 087517149e45
Revises: 20260302_0005
Create Date: 2026-03-03 22:43:23.111022
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '087517149e45'
down_revision: Union[str, None] = '20260302_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_monitoring_serviceID_key', 'ai_monitoring', type_='unique')
    op.drop_constraint('cahier_de_charge_projetID_key', 'cahier_de_charge', type_='unique')
    op.add_column('clients', sa.Column('devise', sa.String(length=10), nullable=False, server_default='TND'))
    op.drop_index('ix_rappels_titre', table_name='rappels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rappels_titre', 'rappels', ['titre'], unique=False)
    op.drop_column('clients', 'devise')
    op.create_unique_constraint('cahier_de_charge_projetID_key', 'cahier_de_charge', ['projetID'])
    op.create_unique_constraint('ai_monitoring_serviceID_key', 'ai_monitoring', ['serviceID'])
    # ### end Alembic commands ###
