"""Add signature fields to contrats

Revision ID: 1a2ac1853f74
Revises: 20260330_0012
Create Date: 2026-03-30 20:02:44.826449
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1a2ac1853f74'
down_revision: Union[str, None] = '20260330_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrats', sa.Column('isSignedByClient', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('contrats', sa.Column('isSignedByProvider', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index('ux_rappels_systemKey', table_name='rappels', postgresql_where='("systemKey" IS NOT NULL)')
    op.create_index(op.f('ix_rappels_systemKey'), 'rappels', ['systemKey'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rappels_systemKey'), table_name='rappels')
    op.create_index('ux_rappels_systemKey', 'rappels', ['systemKey'], unique=True, postgresql_where='("systemKey" IS NOT NULL)')
    op.drop_column('contrats', 'isSignedByProvider')
    op.drop_column('contrats', 'isSignedByClient')
    # ### end Alembic commands ###
