"""add_signature_fields_to_contrat

Revision ID: 2dd060c97b67
Revises: f8246f6a8d30
Create Date: 2026-04-27 22:13:53.716826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2dd060c97b67'
down_revision: Union[str, None] = 'f8246f6a8d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrats', sa.Column('signatureClient', sa.Text(), nullable=True))
    op.add_column('contrats', sa.Column('signatureProvider', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrats', 'signatureProvider')
    op.drop_column('contrats', 'signatureClient')
    # ### end Alembic commands ###
