"""add scoring

Revision ID: 456234d49a72
Revises: 087517149e45
Create Date: 2026-03-04 13:55:35.720974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '456234d49a72'
down_revision: Union[str, None] = '087517149e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projets', sa.Column('scoring', sa.String(length=20), server_default='Moyen', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projets', 'scoring')
    # ### end Alembic commands ###
