"""add avatarUrl to utilisateurs

Revision ID: 4da6b436b1e3
Revises: 1a2ac1853f74
Create Date: 2026-04-01 15:54:10.330069
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4da6b436b1e3'
down_revision: Union[str, None] = '1a2ac1853f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('avatarUrl', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'avatarUrl')
    # ### end Alembic commands ###
