"""add_cnss_and_contract_dates

Revision ID: 58de896e5bcd
Revises: d8eb2111459c
Create Date: 2026-04-10 19:17:51.937591
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '58de896e5bcd'
down_revision: Union[str, None] = 'd8eb2111459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaration_cnss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('frontId', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('declarationDate', sa.DateTime(), nullable=False),
    sa.Column('pdfUrl', sa.String(length=1000), nullable=False),
    sa.Column('pdfPublicId', sa.String(length=300), nullable=False),
    sa.Column('mimeType', sa.String(length=100), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['utilisateurs.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_cnss_createdAt'), 'declaration_cnss', ['createdAt'], unique=False)
    op.create_index(op.f('ix_declaration_cnss_frontId'), 'declaration_cnss', ['frontId'], unique=True)
    op.create_index(op.f('ix_declaration_cnss_id'), 'declaration_cnss', ['id'], unique=False)
    op.create_index(op.f('ix_declaration_cnss_userID'), 'declaration_cnss', ['userID'], unique=False)
    op.add_column('user_contracts', sa.Column('startDate', sa.DateTime(), nullable=True))
    op.add_column('user_contracts', sa.Column('endDate', sa.DateTime(), nullable=True))
    op.drop_constraint('uq_user_contracts_frontId', 'user_contracts', type_='unique')
    op.add_column('utilisateurs', sa.Column('cnssId', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'cnssId')
    op.create_unique_constraint('uq_user_contracts_frontId', 'user_contracts', ['frontId'])
    op.drop_column('user_contracts', 'endDate')
    op.drop_column('user_contracts', 'startDate')
    op.drop_index(op.f('ix_declaration_cnss_userID'), table_name='declaration_cnss')
    op.drop_index(op.f('ix_declaration_cnss_id'), table_name='declaration_cnss')
    op.drop_index(op.f('ix_declaration_cnss_frontId'), table_name='declaration_cnss')
    op.drop_index(op.f('ix_declaration_cnss_createdAt'), table_name='declaration_cnss')
    op.drop_table('declaration_cnss')
    # ### end Alembic commands ###
