"""add_client_portal_user_table

Revision ID: 7113ac7c0758
Revises: 9671b476c7c9
Create Date: 2026-05-12 22:23:43.827618
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7113ac7c0758'
down_revision: Union[str, None] = '9671b476c7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('motDePasse', sa.String(length=255), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clientID'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_portal_users_clientID'), 'client_portal_users', ['clientID'], unique=False)
    op.create_index(op.f('ix_client_portal_users_email'), 'client_portal_users', ['email'], unique=True)
    op.create_index(op.f('ix_client_portal_users_id'), 'client_portal_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_portal_users_id'), table_name='client_portal_users')
    op.drop_index(op.f('ix_client_portal_users_email'), table_name='client_portal_users')
    op.drop_index(op.f('ix_client_portal_users_clientID'), table_name='client_portal_users')
    op.drop_table('client_portal_users')
    # ### end Alembic commands ###
