"""Add AppSettings model

Revision ID: 8d85577a2d36
Revises: 2dd060c97b67
Create Date: 2026-04-30 19:34:25.117805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8d85577a2d36'
down_revision: Union[str, None] = '2dd060c97b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_tax_id', sa.String(length=100), nullable=True),
    sa.Column('company_vat_number', sa.String(length=100), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_email', sa.String(length=150), nullable=True),
    sa.Column('company_reference', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('stamp_url', sa.String(length=500), nullable=True),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_validity_days', sa.Integer(), nullable=True),
    sa.Column('document_notes', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_api_key', sa.String(length=255), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
