"""Add service health monitoring tables

Revision ID: 9441c889ef0d
Revises: ab013806a84b
Create Date: 2026-05-06 17:42:18.951177
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9441c889ef0d'
down_revision: Union[str, None] = 'ab013806a84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_resolved_at'), 'incidents', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_incidents_service_name'), 'incidents', ['service_name'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_table('service_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_checks_checked_at'), 'service_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_service_checks_service_name'), 'service_checks', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_checks_service_name'), table_name='service_checks')
    op.drop_index(op.f('ix_service_checks_checked_at'), table_name='service_checks')
    op.drop_table('service_checks')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_name'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolved_at'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
