"""add_client_id_to_utilisateur

Revision ID: 9671b476c7c9
Revises: d9867495570c
Create Date: 2026-05-12 20:39:47.605942
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9671b476c7c9'
down_revision: Union[str, None] = 'd9867495570c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictive_alerts_alert_type', table_name='predictive_alerts')
    op.drop_index('ix_predictive_alerts_resolved', table_name='predictive_alerts')
    op.drop_table('predictive_alerts')
    op.drop_table('crm_health_scores')
    op.drop_table('simulations')
    op.add_column('app_settings', sa.Column('subscription_plan', sa.String(length=100), nullable=True))
    op.add_column('app_settings', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('app_settings', sa.Column('payment_method_last4', sa.String(length=10), nullable=True))
    op.add_column('app_settings', sa.Column('payment_method_expiry', sa.String(length=20), nullable=True))
    op.add_column('utilisateurs', sa.Column('clientID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'utilisateurs', 'clients', ['clientID'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.drop_column('utilisateurs', 'clientID')
    op.drop_column('app_settings', 'payment_method_expiry')
    op.drop_column('app_settings', 'payment_method_last4')
    op.drop_column('app_settings', 'subscription_status')
    op.drop_column('app_settings', 'subscription_plan')
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scenario', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='simulations_pkey')
    )
    op.create_table('crm_health_scores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crm_health_scores_pkey')
    )
    op.create_table('predictive_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='predictive_alerts_pkey')
    )
    op.create_index('ix_predictive_alerts_resolved', 'predictive_alerts', ['resolved'], unique=False)
    op.create_index('ix_predictive_alerts_alert_type', 'predictive_alerts', ['alert_type'], unique=False)
    # ### end Alembic commands ###
