"""add_oauth_fields_to_utilisateurs

Revision ID: ab013806a84b
Revises: 82c1783544d6
Create Date: 2026-05-05 12:08:04.844601
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ab013806a84b'
down_revision: Union[str, None] = '82c1783544d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('utilisateurs', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.alter_column('utilisateurs', 'motDePasse',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'motDePasse',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('utilisateurs', 'oauth_id')
    op.drop_column('utilisateurs', 'oauth_provider')
    # ### end Alembic commands ###
