"""Add MLPrediction table

Revision ID: d9867495570c
Revises: 9441c889ef0d
Create Date: 2026-05-07 15:07:49.223884
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd9867495570c'
down_revision: Union[str, None] = '9441c889ef0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_prediction_type'), 'ml_predictions', ['prediction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_predictions_prediction_type'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    # ### end Alembic commands ###
