"""add fiscal stamp and tax rate fields to devis and factures

Revision ID: f8246f6a8d30
Revises: cb1243d1f165
Create Date: 2026-04-27 21:53:53.495328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f8246f6a8d30'
down_revision: Union[str, None] = 'cb1243d1f165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('declaration_cnss', 'declarationDate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.add_column('devis', sa.Column('taxRate', sa.Numeric(precision=5, scale=2), server_default='19.0', nullable=False))
    op.add_column('devis', sa.Column('fiscalStamp', sa.Numeric(precision=10, scale=3), server_default='1.0', nullable=False))
    op.add_column('factures', sa.Column('fiscalStamp', sa.Numeric(precision=10, scale=3), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'fiscalStamp')
    op.drop_column('devis', 'fiscalStamp')
    op.drop_column('devis', 'taxRate')
    op.alter_column('declaration_cnss', 'declarationDate',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
